version: "3"
services:
  web:
    build:
      context: ./EmployeesApp/EmployeesApp
      dockerfile: Dockerfile
    volumes:
      - ./EmployeesApp/EmployeesApp:/app
    ports:
      - "8080:5050"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "P@ssw0rd!"
      ACCEPT_EULA: "Y"
