name: .NET Core Windows

on:
  push:
    branches: [ui-testing-selenium, work]
  pull_request:
    branches: [ui-testing-selenium, work]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Install dependencies
        run: dotnet restore ./EmployeesApp/EmployeesApp.sln

      - name: Build
        run: dotnet build ./EmployeesApp/EmployeesApp.sln --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish -c Release -o output EmployeesApp/EmployeesApp.sln --no-restore

      - name: Unit Test
        working-directory: ./output
        run: dotnet vstest EmployeesApp.Tests.dll

      - name: Integrations Test
        working-directory: ./output
        run: dotnet vstest EmployeesApp.IntegrationTests.dll

      - name: Docker-compose
        working-directory: EmployeesApp/EmployeesApp
        run: |
          docker-compose run --rm start_dependencies
          docker-compose up -d --remove-orphans  web
          docker-compose ps

      - name: AutomatedUITests
        working-directory: ./output
        run: |
          dotnet vstest EmployeesApp.AutomatedUITests.dll

      - name: Compress output
        run: tar -zcvf output.tar.gz ./output

      - name: uploading...
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: output.tar.gz
