version: "3"
services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    environment:
      - SLEEP_LENGTH=1
      - TIMEOUT_LENGTH=10
    depends_on:
      - db
    command: db:1433
  web:
    build:
      context: .
      dockerfile: Dockerfile.Runtime
    ports:
      - "8080:5050"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "P@ssw0rd!"
      ACCEPT_EULA: "Y"
