name: Build msbuild

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout Code

      - name: List Workspace variable
        run: echo  "%GITHUB_WORKSPACE%"
      - name: List Workspace variable
        run: ls  "%GITHUB_WORKSPACE%"

      - name: List CD
        run: echo  "%CD%"
      - name: List ls
        run: ls  "%CD%"

      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore NuGet Packages
        run: nuget restore EmployeesApp\EmployeesApp.sln

      - name: List Workspace variable
        run: echo  "%GITHUB_WORKSPACE%"

      - name: List CD
        run: echo  "%CD%"

      - name: Build and Publish Web App
        run: msbuild EmployeesApp\EmployeesApp.sln /t:Restore /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

        # look for dacpac
      - name: find dacpac
        run: |
          echo "ls my project\bin\Debug\"
          ls "%GITHUB_WORKSPACE%\EmployeesApp\bin\Release"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: published_webapp
          path: bin\Release\Publish
