name: .NET Core Ubuntu Docker

on:
  push:
    branches: [ui-testing-selenium]
  pull_request:
    branches: [ui-testing-selenium]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Install dependencies
        run: dotnet restore ./EmployeesApp/EmployeesApp.sln

      - name: Build
        run: dotnet build ./EmployeesApp/EmployeesApp.sln --configuration Release --no-restore

      - name: Unit Test
        run: dotnet test --no-restore --verbosity normal EmployeesApp/EmployeesApp.Tests

      - name: Integrations Test
        run: dotnet test --no-restore --verbosity normal EmployeesApp/EmployeesApp.IntegrationTests

      - name: Docker-compose
        run: |
          docker-compose up -d
          docker-compose ps

      - name: UITest
        run: |
          docker-compose ps
          dotnet test --no-restore --verbosity normal EmployeesApp/EmployeesApp.AutomatedUITests

      - name: Publish
        run: |
          dotnet publish -c Release -o output EmployeesApp/EmployeesApp.sln

      - name: Compress output
        run: tar -zcvf output.tar.gz ./output

      - uses: actions/upload-artifact@v2
        with:
          name: UbuntuDocker
          path: output.tar.gz
