name: .NET Core Ubuntu

on:
  push:
    branches: [ui-testing-selenium]
  pull_request:
    branches: [ui-testing-selenium]

jobs:
  e2etest:
    needs: [build, tests, setupMSSql]
    runs-on: ubuntu-18.04
    steps:
      - name: Setup MSSql
        run: |
          chmod +x ./setupDB.sh
          ./setupDB.sh
        shell: bash
      - name: Download Output folder
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: untar app
        run: tar -xvf output.tar.gz

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Start Server And Run Test
        working-directory: ./output
        run: |
          (./EmployeesApp)&  (dotnet vstest EmployeesApp.AutomatedUITests.dll)
        shell: bash

  buildAppAndRunTests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Install dependencies
        run: dotnet restore ./EmployeesApp/EmployeesApp.sln

      - name: Build
        run: dotnet build ./EmployeesApp/EmployeesApp.sln --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish -c Release -o output EmployeesApp/EmployeesApp.sln --no-restore

      - name: Unit Test
        working-directory: ./output
        run: dotnet vstest EmployeesApp.Tests.dll
      - name: Integrations Test
        working-directory: ./output
        run: dotnet vstest EmployeesApp.IntegrationTests.dll

      - name: Compress output
        run: tar -zcvf output.tar.gz ./output

      - name: uploading...
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: output.tar.gz
