name: Ubuntu_Docker

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          
      - name: Restore sln
        run: dotnet restore EmployeesApp/EmployeesApp.sln
      
      - name: Publish
        run: |
          dotnet publish -c Release -o output EmployeesApp/EmployeesApp.sln --no-restore
      
      - name: Unit Test
        working-directory: ./output
        run: dotnet vstest EmployeesApp.Tests.dll
      
      - name: Integrations Test
        working-directory: ./output
        run: dotnet vstest EmployeesApp.IntegrationTests.dll

      - name: AutomatedUITests
        working-directory: ./output
        run: |
          docker-compose ps
          dotnet vstest EmployeesApp.AutomatedUITests.dll

      - name: Compress output
        run: tar -zcvf output.tar.gz ./output

      - uses: actions/upload-artifact@v2
        with:
          name: UbuntuDocker
          path: output.tar.gz
